version: 2

before:
  hooks:
    - go mod tidy
    - sh -c "cd frontend && npm install --legacy-peer-deps && npm run build"

builds:
  - id: tailtunnel
    main: ./cmd/tailtunnel
    binary: tailtunnel
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.Version={{.Version}}"

archives:
  - id: tailtunnel
    format: tar.gz
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    rlcp: true
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Use the new homebrews syntax instead of brews
homebrews:
  - name: tailtunnel
    repository:
      owner: rajsinghtech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Raj Singh
      email: rajsinghcpre@gmail.com
    directory: Formula
    homepage: "https://github.com/rajsinghtech/tailtunnel"
    description: "A web dashboard for your Tailscale network with browser-based SSH and network diagnostics"
    license: "MIT"
    dependencies:
      - name: node
        type: build
