version: 2

before:
  hooks:
    - go mod tidy
    - sh -c "cd frontend && npm install --legacy-peer-deps && npm run build"

builds:
  - id: tailtunnel
    main: ./cmd/tailtunnel
    binary: tailtunnel
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.Version={{.Version}}"

archives:
  - id: tailtunnel
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  header: |
    ## Installation

    ### macOS App (Recommended for Desktop)
    ```bash
    brew install --cask rajsinghtech/tap/tailtunnel
    ```

    Or download `TailTunnel.zip` manually, unzip, and drag to `/Applications`.

    ### CLI Binary (Servers/Headless)
    ```bash
    brew install rajsinghtech/tap/tailtunnel
    ```

    ### Docker

    Pull the multi-arch image:
    ```bash
    docker pull ghcr.io/rajsinghtech/tailtunnel:{{ .Tag }}
    ```

    Run with Docker:
    ```bash
    docker run -d \
      --name tailtunnel \
      -e TS_AUTHKEY=your-key-here \
      -v tailtunnel-state:/var/lib/tailtunnel \
      ghcr.io/rajsinghtech/tailtunnel:{{ .Tag }}
    ```

    See the [README](https://github.com/rajsinghtech/tailtunnel) for more installation options.

    ## Verification

    The container image has been signed with Cosign and includes an SBOM (attached to this release).

    ## What's New

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# CLI binary formula (macOS app cask is handled by build-macos.yml workflow)
brews:
  - name: tailtunnel
    ids:
      - tailtunnel
    repository:
      owner: rajsinghtech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    commit_author:
      name: Raj Singh
      email: rajsinghcpre@gmail.com
    homepage: "https://github.com/rajsinghtech/tailtunnel"
    description: "A web dashboard for Tailscale with browser-based SSH and network diagnostics"
    license: "MIT"
    dependencies:
      - name: node
